#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = new Symfony\Component\Console\Application('Just a Phone CLI', 'dev');
$app->add(new Just\DNDCommand);
$app->add(new Just\CallCommand);
$app->add(new Just\VolumeCommand);

$app->run();
